import React, { useState } from 'react';

const IWANTCLO: React.FC = () => {////I JUST WANT TO AKE A LONG BATH AND READ "NUMBER GO UP" BY ZEKE FAUX
    const [text, setText] = useState<string>(''); ////THIS IS PARTICALRLY BORORwed

    const handleClick = () => { ///THIS CLASS MADE ME BREAK UP WITH MY COMPSCI EGGHEADED BOYFRIEND 
        setText('ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOYALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY ALL CODE AND NO CLOTHES MAKES JACK A DULL BOY '
       
    
        );
    };

    return (
        <div>
            <button onClick={handleClick}>Click Me</button>
            <p style={{ fontSize: '67px', fontFamily: 'Arial, sans-serif' }}>{text}</p>
        </div>
    );
};

export default IWANTCLO; 